### ISSUE TITLE
No such module 'UIKit'

### ISSUE THREAD

**Issue by Matthewspear** [klaaspieter/coc-sourcekit#10]
I am aware it is still early days for sourcekit-lsp, I'm try to use autocomplete for iOS development under vim.

I saw the previously closed issue #6 with support / a workaround for UIKit support.
I managed to get it working for swift packages and in VSCode through the example but not files in a project.

Is this expected behaviour or am I missing something?

**Comment by ThangaAyyanar** [comment]
This is expected behaviour
```
There is no officially supported way to understand Xcode projects outside of Xcode, for example there is nothing like 
libSwiftPM which the SwiftPM team commits to support as a way of understanding SwiftPM projects. 
Unless this situation changes, we do not intend to support Xcode projects outside of the Xcode IDE. 
Xcode itself will change to provide its settings directly to sourcekit-lsp, when used from inside the IDE.

People have devised methods for getting a compilation database out of an Xcode project, 
you may want to look into these, the compilation database is something we intend to maintain first-class support for.
```
from this link https://forums.swift.org/t/whats-the-plan-for-index/18441/4

**Comment by Matthewspear** [comment]
Ok sorry, what I'm really looking for is a way to autocomplete Swift files including linked functions (relative to project folder) and iOS / macOS frameworks like UIKit / AppKit.

For building / running I'll either open Xcode, Xcode server or use `xcrun`
Is that currently possible via `coc-sourcekit`?

I've found UIKit the main problem, my current workaround being to copy a file into a swift package environment, edit it and then return it back into my Xcode project but I'm hoping there is an easier way :)

**Comment by ThangaAyyanar** [comment]
I guess we can provide completion feature for xcode project by generating **build index** and made it available to SourceKit-LSP. Found this while exploring in swift forums,Sourcekit repo. I haven't tried it yet.
```
USAGE: sourcekit-lsp [options]

OPTIONS:
  --build-path          Specify build/cache directory
  --configuration, -c   Build with configuration (debug|release) [default: debug]
  --log-level           Set the logging level (debug|info|warning|error) [default: info]
  -Xcc                  Pass flag through to all C compiler invocations
  -Xclangd              Pass options to clangd command-line
  -Xcxx                 Pass flag through to all C++ compiler invocations
  -Xlinker              Pass flag through to all linker invocations
  -Xswiftc              Pass flag through to all Swift compiler invocations
  -index-db-path        Override index-database-path from the build system
  -index-store-path     Override index-store-path from the build system
  --help                Display available options```

For building or running 
- As of now it is not possible to generate build from coc-sourcekit.
- You can create a simple shell script and invoke it from vim.(My opinion)

**Comment by Matthewspear** [comment]
Thanks @ThangaAyyanar – I'll look into it and if anything can be contributed back I'll try to post it in this issue!
