### ISSUE TITLE
How to get this to work for iOS apps

### ISSUE THREAD

**Issue by lanza** [klaaspieter/coc-sourcekit#19]
1. You need a `Package.swift` dummy file. `sourcekit-lsp` only works for non-trivial setups if there's a package defined for that source file. So put all your sources in a directory and add a `Package.swift` file. 

2. You need something like this in your coc.nvim settings:

```
"sourcekit.sdk": "iphonesimulator",
"sourcekit.targetArch": "x86_64-apple-ios14.3-simulator"
```

**Comment by konrad1977** [comment]
Could you give an example on such dummy file?
