### ISSUE TITLE
How to use this extension

### ISSUE THREAD

**Issue by Zeta611** [klaaspieter/coc-sourcekit#4]
Hi, I've installed Swift Development Snapshot Toolchain and set Xcode to use it.
However, when I open a Swift file in Neovim, coc-sourcekit doesn't start.
`:CocCommand workspace.showOutput` doesn't show the language server as an option.

`xcrun --toolchain swift --find sourcekit-lsp` correctly shows: 
`/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2020-02-21-a.xctoolchain/usr/bin/sourcekit-lsp`

**Comment by Zeta611** [comment]
It started to work after I installed [keith/swift.vim](https://github.com/keith/swift.vim). Is it an expected behavior?

**Comment by klaaspieter** [comment]
I have https://github.com/keith/swift.vim installed through [vim-polyglot](https://github.com/sheerun/vim-polyglot) so it isn't entirely impossible. I've done some testing and it looks like without swift.vim installed vim does not know about the swift filetype. If you don't want swift.vim installed you could try manually setting the file type to swift (`:setf swift`)?  If that solves it for you than you should be able to use your auto command to set the correct file type: [`autocmd BufNewFile,BufRead *.swift set filetype=swift`](https://github.com/keith/swift.vim/blob/master/ftdetect/swift.vim#L1).

I suspect once you've set the correct file type `CocCommand workspace.showOutput` will give you some more information.

**Comment by klaaspieter** [comment]
I updated the README with this information (https://github.com/klaaspieter/coc-sourcekit/commit/5585ae63c528f6020dde5c7e74ba394f32a02f16).

**Comment by Zeta611** [comment]
Thank you for verifying! I actually need swift.vim installed, so I’m happy with my setup.
