### ISSUE TITLE
no Module found UIKit

### ISSUE THREAD

**Issue by ThangaAyyanar** [klaaspieter/coc-sourcekit#6]
I found a hack which make iOS Module work in vscode, can we able to make it work for coc-sourcekit

https://funnyitworkedlasttime.dev/posts/2020-01-10-swift-vscode-sourcekit-lsp/

**Comment by klaaspieter** [comment]
This seems neat. Can you open a PR?

**Comment by ThangaAyyanar** [comment]
Sure

**Comment by ThangaAyyanar** [comment]
Can you take a look at PR? I have few doubts.

**Comment by klaaspieter** [comment]
PR was merged.
